# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: selenide
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "selenide_new" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "jselenide"
github_username: "codeborne/selenide"

current_version: "4.12.0"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-polyglot
  # - jekyll-coffeescript

defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      menu_order: 100
      lang: 'en'

languages: ["en", "ru"]
default_lang: "en"
exclude_from_localization: ["js", "img", "css"]
parallel_localization: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - util_node_js
  - Gemfile
  - Gemfile.lock
  - README.md
  - svg-icons
  - logo
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
